# Generated by Django 6.0.4 on 2026-04-20 10:19

import common.mixins
import common.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('universes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True, validators=[common.validators.ImageURLValidator()])),
                ('description', models.TextField()),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Name must contain only Latin letters. You can use a single space, hyphen, or apostrophe between words.', regex="^[A-Za-z]+(?:[ '-][A-Za-z]+)*$"), django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Name must contain only Latin letters. You can use a single space, hyphen, or apostrophe between words.', regex="^[A-Za-z]+(?:[ '-][A-Za-z]+)*$"), django.core.validators.MinLengthValidator(2)])),
                ('role', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='locations.location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='universes.universe')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('slug', 'universe'), name='unique_character_slug_per_universe')],
            },
            bases=(common.mixins.SlugMixin, models.Model),
        ),
    ]
