# Generated by Django 6.0.3 on 2026-03-16 21:09

import common.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('universes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, validators=[common.validators.ImageURLValidator()])),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="Please use only letters, with a hyphen, space, or apostrophe. Numbers and symbols aren't allowed.", regex="^[^\\W\\d_]+(?:[ '-][^\\W\\d_]+)*$")])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="Please use only letters, with a hyphen, space, or apostrophe. Numbers and symbols aren't allowed.", regex="^[^\\W\\d_]+(?:[ '-][^\\W\\d_]+)*$")])),
                ('role', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='locations.location')),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='universes.universe')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('slug', 'universe'), name='unique_character_slug_per_universe')],
            },
        ),
    ]
