# Generated by Django 6.0.4 on 2026-04-15 10:39

import common.mixins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        ('universes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('characters', models.ManyToManyField(blank=True, related_name='stories', to='characters.character')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='universes.universe')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('title', 'universe'), name='unique_title_per_universe'), models.UniqueConstraint(fields=('slug', 'universe'), name='unique_story_slug_per_universe')],
            },
            bases=(common.mixins.SlugMixin, models.Model),
        ),
    ]
