# Generated by Django 6.0.3 on 2026-03-16 21:09

import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Genre must be at least 3 characters long.'), django.core.validators.RegexValidator(message='Genre must contain only letters, with a single space or hyphen between words.', regex='^[a-zA-Z]+(?:[ -][a-zA-Z]+)*$')])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, validators=[common.validators.ImageURLValidator()])),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message="Please use only letters, with a hyphen, space, or apostrophe. Numbers and symbols aren't allowed.", regex="^[^\\W\\d_]+(?:[ '-][^\\W\\d_]+)*$")])),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='universes', to='universes.genre')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_universe_name'), models.UniqueConstraint(fields=('slug',), name='unique_universe_slug')],
            },
        ),
    ]
