# Generated by Django 6.0.3 on 2026-03-14 15:32

import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'Genre name must be at least 3 characters long.'), common.validators.NameValidator()])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, validators=[common.validators.ImageURLValidator()])),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, validators=[common.validators.NameValidator()])),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='universes', to='universes.genre')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_universe_name')],
            },
        ),
    ]
