# Generated by Django 6.0.4 on 2026-04-15 10:27

import common.mixins
import common.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True, validators=[common.validators.ImageURLValidator()])),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message="Please use only letters, with a single hyphen, space, or apostrophe. Numbers and symbols aren't allowed.", regex="^[^\\W\\d_]+(?:[ '-][^\\W\\d_]+)*$")])),
                ('type', models.CharField(choices=[('Planet', 'Planet'), ('Continent', 'Continent'), ('Country', 'Country'), ('Region', 'Region'), ('City', 'City'), ('District', 'District'), ('Building', 'Building'), ('Wilderness', 'Wilderness'), ('Other', 'Other')], max_length=50)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
                ('parent_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_locations', to='locations.location')),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='universes.universe')),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('name', 'universe'), name='unique_name_per_universe'), models.UniqueConstraint(fields=('slug', 'universe'), name='unique_location_slug_per_universe')],
            },
            bases=(common.mixins.SlugMixin, models.Model),
        ),
    ]
